CREATE OR REPLACE WAREHOUSE PLACEMENT_WH
WITH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE STUDENT_PLACEMENT_DB;

USE DATABASE STUDENT_PLACEMENT_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA ANALYTICS;

USE WAREHOUSE PLACEMENT_WH;
USE DATABASE STUDENT_PLACEMENT_DB;
USE SCHEMA RAW;