USE DATABASE STUDENT_PLACEMENT_DB;
USE SCHEMA RAW;

-- RAW STUDENTS TABLE
CREATE OR REPLACE TABLE RAW_STUDENTS (
    STUDENT_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    PROGRAM VARCHAR,
    BRANCH VARCHAR,
    GRAD_YEAR NUMBER,
    CGPA FLOAT,
    SEGMENT VARCHAR,
    COLLEGE_ID VARCHAR
);

-- RAW COLLEGES TABLE
CREATE OR REPLACE TABLE RAW_COLLEGES (
    COLLEGE_ID VARCHAR,
    COLLEGE_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    OWNERSHIP VARCHAR,
    TIER VARCHAR,
    CATEGORY VARCHAR,
    ESTABLISHED_DATE DATE,
    STATUS VARCHAR
);

-- RAW COMPANIES TABLE
CREATE OR REPLACE TABLE RAW_COMPANIES (
    COMPANY_ID VARCHAR,
    COMPANY_NAME VARCHAR,
    INDUSTRY VARCHAR,
    COMPANY_SIZE_BAND VARCHAR,
    HIRING_CITY VARCHAR,
    HIRING_STATE VARCHAR,
    COUNTRY VARCHAR,
    STATUS VARCHAR
);

-- RAW OFFERS TABLE
CREATE OR REPLACE TABLE RAW_OFFERS (
    OFFER_ID VARCHAR,
    OFFER_LINE_ID NUMBER,
    OFFER_DATE DATE,
    STUDENT_ID VARCHAR,
    COMPANY_ID VARCHAR,
    COLLEGE_ID VARCHAR,
    ROLE_TITLE VARCHAR,
    OFFER_LEVEL VARCHAR,
    CTC_LPA FLOAT,
    MONTHLY_STIPEND FLOAT,
    JOB_CITY VARCHAR,
    HIRING_MODE VARCHAR,
    OFFER_STATUS VARCHAR,
    IS_JOINED NUMBER
);