USE DATABASE STUDENT_PLACEMENT_DB;
USE SCHEMA ANALYTICS;

-- ============================================
-- DIMENSION: STUDENT
-- SCD TYPE 2 STRUCTURE
-- ============================================

CREATE OR REPLACE TABLE DIM_STUDENT (

    STUDENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,

    STUDENT_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    PROGRAM VARCHAR,
    BRANCH VARCHAR,
    GRAD_YEAR NUMBER,
    CGPA FLOAT,
    SEGMENT VARCHAR,
    COLLEGE_ID VARCHAR,

    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);


-- ============================================
-- DIMENSION: COMPANY
-- SCD TYPE 2 STRUCTURE
-- ============================================

CREATE OR REPLACE TABLE DIM_COMPANY (

    COMPANY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,

    COMPANY_ID VARCHAR,
    COMPANY_NAME VARCHAR,
    INDUSTRY VARCHAR,
    COMPANY_SIZE_BAND VARCHAR,
    HIRING_CITY VARCHAR,
    HIRING_STATE VARCHAR,
    COUNTRY VARCHAR,
    STATUS VARCHAR,

    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);


-- ============================================
-- DIMENSION: COLLEGE
-- ============================================

CREATE OR REPLACE TABLE DIM_COLLEGE (

    COLLEGE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,

    COLLEGE_ID VARCHAR,
    COLLEGE_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    OWNERSHIP VARCHAR,
    TIER VARCHAR,
    CATEGORY VARCHAR,
    ESTABLISHED_DATE DATE,
    STATUS VARCHAR
);


-- ============================================
-- DIMENSION: DATE
-- ============================================

CREATE OR REPLACE TABLE DIM_DATE (

    DATE_KEY NUMBER PRIMARY KEY,

    FULL_DATE DATE,
    DAY_NUMBER NUMBER,
    DAY_NAME VARCHAR,

    MONTH_NUMBER NUMBER,
    MONTH_NAME VARCHAR,

    QUARTER_NUMBER NUMBER,
    YEAR_NUMBER NUMBER
);