USE DATABASE STUDENT_PLACEMENT_DB;
USE SCHEMA ANALYTICS;

-- ============================================
-- FACT: PLACEMENT
-- Grain:
-- One row per OFFER_ID + OFFER_LINE_ID
-- ============================================

CREATE OR REPLACE TABLE FACT_PLACEMENT (

    PLACEMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,

    OFFER_ID VARCHAR,
    OFFER_LINE_ID NUMBER,

    DATE_KEY NUMBER,
    STUDENT_KEY NUMBER,
    COMPANY_KEY NUMBER,
    COLLEGE_KEY NUMBER,

    ROLE_TITLE VARCHAR,
    OFFER_LEVEL VARCHAR,

    CTC_LPA FLOAT,
    MONTHLY_STIPEND FLOAT,

    JOB_CITY VARCHAR,
    HIRING_MODE VARCHAR,

    OFFER_STATUS VARCHAR,
    IS_JOINED NUMBER,

    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()

);