USE DATABASE STUDENT_PLACEMENT_DB;
USE SCHEMA ANALYTICS;


-- ============================================
-- MAIN PLACEMENT ANALYTICS VIEW
-- ============================================

CREATE OR REPLACE VIEW VW_PLACEMENT_ANALYTICS AS

SELECT

    f.OFFER_ID,
    f.OFFER_LINE_ID,

    d.FULL_DATE AS OFFER_DATE,
    d.YEAR_NUMBER,
    d.MONTH_NAME,
    d.QUARTER_NUMBER,

    s.STUDENT_ID,
    s.FIRST_NAME,
    s.LAST_NAME,
    s.GENDER,
    s.PROGRAM,
    s.BRANCH,
    s.GRAD_YEAR,
    s.CGPA,
    s.SEGMENT,

    col.COLLEGE_ID,
    col.COLLEGE_NAME,
    col.CITY AS COLLEGE_CITY,
    col.STATE AS COLLEGE_STATE,
    col.TIER AS COLLEGE_TIER,
    col.CATEGORY AS COLLEGE_CATEGORY,

    c.COMPANY_ID,
    c.COMPANY_NAME,
    c.INDUSTRY,
    c.COMPANY_SIZE_BAND,
    c.HIRING_CITY,

    f.ROLE_TITLE,
    f.OFFER_LEVEL,
    f.CTC_LPA,
    f.MONTHLY_STIPEND,
    f.JOB_CITY,
    f.HIRING_MODE,
    f.OFFER_STATUS,
    f.IS_JOINED

FROM FACT_PLACEMENT f

LEFT JOIN DIM_DATE d
    ON f.DATE_KEY = d.DATE_KEY

LEFT JOIN DIM_STUDENT s
    ON f.STUDENT_KEY = s.STUDENT_KEY

LEFT JOIN DIM_COMPANY c
    ON f.COMPANY_KEY = c.COMPANY_KEY

LEFT JOIN DIM_COLLEGE col
    ON f.COLLEGE_KEY = col.COLLEGE_KEY;


-- ============================================
-- EXECUTIVE SUMMARY VIEW
-- ============================================

CREATE OR REPLACE VIEW VW_EXECUTIVE_SUMMARY AS

SELECT

    COUNT(*) AS TOTAL_OFFERS,

    COUNT(DISTINCT STUDENT_ID) AS STUDENTS_PLACED,

    COUNT(DISTINCT COMPANY_ID) AS COMPANIES_HIRING,

    COUNT(DISTINCT COLLEGE_ID) AS COLLEGES_WITH_PLACEMENTS,

    ROUND(AVG(CTC_LPA), 2) AS AVG_CTC_LPA,

    ROUND(MAX(CTC_LPA), 2) AS HIGHEST_CTC_LPA,

    SUM(IS_JOINED) AS TOTAL_JOINED,

    ROUND(
        (SUM(IS_JOINED) / COUNT(*)) * 100,
        2
    ) AS JOIN_RATE_PERCENT

FROM VW_PLACEMENT_ANALYTICS;


-- ============================================
-- COLLEGE PERFORMANCE VIEW
-- ============================================

CREATE OR REPLACE VIEW VW_COLLEGE_PERFORMANCE AS

SELECT

    COLLEGE_ID,
    COLLEGE_NAME,
    COLLEGE_CITY,
    COLLEGE_STATE,
    COLLEGE_TIER,

    COUNT(*) AS TOTAL_OFFERS,

    COUNT(DISTINCT STUDENT_ID) AS STUDENTS_PLACED,

    ROUND(AVG(CTC_LPA), 2) AS AVG_CTC_LPA,

    ROUND(MAX(CTC_LPA), 2) AS HIGHEST_CTC_LPA,

    SUM(IS_JOINED) AS STUDENTS_JOINED

FROM VW_PLACEMENT_ANALYTICS

GROUP BY

    COLLEGE_ID,
    COLLEGE_NAME,
    COLLEGE_CITY,
    COLLEGE_STATE,
    COLLEGE_TIER;


-- ============================================
-- COMPANY INSIGHTS VIEW
-- ============================================

CREATE OR REPLACE VIEW VW_COMPANY_INSIGHTS AS

SELECT

    COMPANY_ID,
    COMPANY_NAME,
    INDUSTRY,
    COMPANY_SIZE_BAND,
    HIRING_CITY,

    COUNT(*) AS TOTAL_OFFERS,

    COUNT(DISTINCT STUDENT_ID) AS STUDENTS_HIRED,

    ROUND(AVG(CTC_LPA), 2) AS AVG_CTC_LPA,

    ROUND(MAX(CTC_LPA), 2) AS HIGHEST_CTC_LPA,

    SUM(IS_JOINED) AS TOTAL_JOINED

FROM VW_PLACEMENT_ANALYTICS

GROUP BY

    COMPANY_ID,
    COMPANY_NAME,
    INDUSTRY,
    COMPANY_SIZE_BAND,
    HIRING_CITY;


-- ============================================
-- PLACEMENT EXPLORER VIEW
-- ============================================

CREATE OR REPLACE VIEW VW_PLACEMENT_EXPLORER AS

SELECT *

FROM VW_PLACEMENT_ANALYTICS;


-- ============================================
-- DATA QUALITY SUMMARY VIEW
-- ============================================

CREATE OR REPLACE VIEW VW_DATA_QUALITY_SUMMARY AS

SELECT

    (SELECT COUNT(*)
     FROM STUDENT_PLACEMENT_DB.RAW.RAW_OFFERS
    ) AS RAW_OFFERS,

    (SELECT COUNT(*)
     FROM STUDENT_PLACEMENT_DB.STAGING.STG_PLACEMENT_PYSPARK
    ) AS PYSPARK_STAGING_RECORDS,

    (SELECT COUNT(*)
     FROM FACT_PLACEMENT
    ) AS FACT_RECORDS,

    (SELECT COUNT(*)
     FROM FACT_PLACEMENT
     WHERE CTC_LPA <= 0
        OR CTC_LPA >= 100
        OR CTC_LPA IS NULL
    ) AS INVALID_CTC_RECORDS,

    (SELECT COUNT(*)
     FROM FACT_PLACEMENT
     WHERE OFFER_ID IS NULL
        OR STUDENT_KEY IS NULL
        OR COMPANY_KEY IS NULL
        OR COLLEGE_KEY IS NULL
    ) AS CRITICAL_FIELD_ERRORS;